// Strength Training Routines
// Focused on building muscle and strength using home gym equipment

import type { WorkoutRoutine } from './types';

export const STRENGTH_ROUTINES: WorkoutRoutine[] = [
  // ============================================
  // PUSH/PULL/LEGS SPLIT
  // ============================================
  {
    id: 'strength-push-day',
    name: 'Push Day - Chest, Shoulders, Triceps',
    description:
      'Upper body pushing movements targeting chest, shoulders, and triceps. Part of a PPL split.',
    category: 'strength',
    difficulty: 'intermediate',
    duration_minutes: 55,
    equipment_needed: ['Olympic Barbell', 'Incline Bench', 'Adjustable Dumbbells', 'Squat Rack'],
    target_muscles: ['Chest', 'Shoulders', 'Triceps'],
    rest_between_exercises_seconds: 90,
    warmup: [
      'Arm circles - 30 seconds each direction',
      'Band pull-aparts or light dumbbell flyes - 15 reps',
      'Push-ups - 10 reps',
      'Empty barbell bench press - 10 reps',
    ],
    exercises: [
      {
        name: 'Barbell Bench Press',
        sets: 4,
        reps: '6-8',
        weight_suggestion: 'heavy',
        rest_seconds: 120,
        notes: 'Keep shoulder blades retracted and feet firmly planted',
        alternatives: ['Dumbbell Bench Press', 'Floor Press'],
      },
      {
        name: 'Incline Dumbbell Press',
        sets: 3,
        reps: '8-10',
        weight_suggestion: 'moderate',
        rest_seconds: 90,
        notes: 'Set bench to 30-45 degree angle',
        alternatives: ['Incline Barbell Press'],
      },
      {
        name: 'Overhead Press',
        sets: 4,
        reps: '6-8',
        weight_suggestion: 'heavy',
        rest_seconds: 120,
        notes: 'Brace core, squeeze glutes, press straight up',
        alternatives: ['Seated Dumbbell Press', 'Arnold Press'],
      },
      {
        name: 'Dumbbell Lateral Raises',
        sets: 3,
        reps: '12-15',
        weight_suggestion: 'light',
        rest_seconds: 60,
        notes: 'Control the negative, slight bend in elbows',
        alternatives: ['Cable Lateral Raises'],
      },
      {
        name: 'Dumbbell Tricep Overhead Extension',
        sets: 3,
        reps: '10-12',
        weight_suggestion: 'moderate',
        rest_seconds: 60,
        notes: 'Keep elbows close to head, full range of motion',
        alternatives: ['Skull Crushers', 'Tricep Dips'],
      },
      {
        name: 'Diamond Push-ups',
        sets: 3,
        reps: '12-15',
        weight_suggestion: 'bodyweight',
        rest_seconds: 60,
        notes: 'Hands form diamond shape, focus on triceps',
        alternatives: ['Close-Grip Bench Press'],
      },
    ],
    cooldown: ['Chest doorway stretch - 30 seconds each side', 'Tricep stretch - 30 seconds each arm'],
    tags: ['push', 'ppl', 'upper-body', 'chest', 'shoulders', 'triceps', 'muscle-building'],
  },

  {
    id: 'strength-pull-day',
    name: 'Pull Day - Back and Biceps',
    description: 'Upper body pulling movements targeting back and biceps. Part of a PPL split.',
    category: 'strength',
    difficulty: 'intermediate',
    duration_minutes: 55,
    equipment_needed: ['Olympic Barbell', 'Adjustable Dumbbells', 'Squat Rack'],
    target_muscles: ['Back', 'Biceps'],
    rest_between_exercises_seconds: 90,
    warmup: [
      'Cat-cow stretches - 10 reps',
      'Band pull-aparts - 15 reps',
      'Light dumbbell rows - 10 reps each arm',
      'Scapular retractions - 15 reps',
    ],
    exercises: [
      {
        name: 'Barbell Rows',
        sets: 4,
        reps: '6-8',
        weight_suggestion: 'heavy',
        rest_seconds: 120,
        notes: 'Hinge at hips, pull to lower chest, squeeze shoulder blades',
        alternatives: ['Pendlay Rows', 'T-Bar Rows'],
      },
      {
        name: 'Pull-ups',
        sets: 4,
        reps: '6-10',
        weight_suggestion: 'bodyweight',
        rest_seconds: 90,
        notes: 'Full dead hang to chin over bar. Use rack for assisted if needed',
        alternatives: ['Lat Pulldown', 'Inverted Rows'],
      },
      {
        name: 'Single-Arm Dumbbell Rows',
        sets: 3,
        reps: '10-12',
        weight_suggestion: 'moderate',
        rest_seconds: 60,
        notes: 'Brace on bench, pull elbow past torso',
        alternatives: ['Chest-Supported Rows'],
      },
      {
        name: 'Face Pulls (with bands or light dumbbells)',
        sets: 3,
        reps: '15-20',
        weight_suggestion: 'light',
        rest_seconds: 60,
        notes: 'External rotation at top, focus on rear delts',
        alternatives: ['Reverse Flyes'],
      },
      {
        name: 'Barbell Curls',
        sets: 3,
        reps: '10-12',
        weight_suggestion: 'moderate',
        rest_seconds: 60,
        notes: 'Keep elbows pinned, control the negative',
        alternatives: ['EZ Bar Curls'],
      },
      {
        name: 'Hammer Curls',
        sets: 3,
        reps: '12-15',
        weight_suggestion: 'moderate',
        rest_seconds: 60,
        notes: 'Neutral grip, targets brachialis',
        alternatives: ['Cross-Body Hammer Curls'],
      },
    ],
    cooldown: ['Lat stretch on rack - 30 seconds each side', 'Bicep wall stretch - 30 seconds each arm'],
    tags: ['pull', 'ppl', 'upper-body', 'back', 'biceps', 'muscle-building'],
  },

  {
    id: 'strength-legs-day',
    name: 'Legs Day - Quads, Hamstrings, Glutes',
    description: 'Lower body focused day with compound and isolation movements. Part of a PPL split.',
    category: 'strength',
    difficulty: 'intermediate',
    duration_minutes: 60,
    equipment_needed: ['Olympic Barbell', 'Squat Rack', 'Safety Bars', 'Adjustable Dumbbells'],
    target_muscles: ['Quadriceps', 'Hamstrings', 'Glutes', 'Calves'],
    rest_between_exercises_seconds: 120,
    warmup: [
      'Leg swings - 15 each direction',
      'Bodyweight squats - 15 reps',
      'Walking lunges - 10 each leg',
      'Hip circles - 10 each direction',
    ],
    exercises: [
      {
        name: 'Barbell Back Squat',
        sets: 4,
        reps: '5-6',
        weight_suggestion: 'heavy',
        rest_seconds: 180,
        notes: 'Brace core, break at hips and knees together, depth to parallel or below',
        alternatives: ['Front Squat', 'Goblet Squat'],
      },
      {
        name: 'Romanian Deadlifts',
        sets: 4,
        reps: '8-10',
        weight_suggestion: 'moderate',
        rest_seconds: 120,
        notes: 'Soft knee bend, hinge at hips, feel hamstring stretch',
        alternatives: ['Stiff-Leg Deadlifts', 'Good Mornings'],
      },
      {
        name: 'Walking Lunges',
        sets: 3,
        reps: '12 each leg',
        weight_suggestion: 'moderate',
        rest_seconds: 90,
        notes: 'Keep torso upright, knee tracks over toe',
        alternatives: ['Reverse Lunges', 'Bulgarian Split Squats'],
      },
      {
        name: 'Leg Press (use squat rack for hack squat variation)',
        sets: 3,
        reps: '10-12',
        weight_suggestion: 'moderate',
        rest_seconds: 90,
        notes: 'Can do heel-elevated goblet squats as alternative',
        alternatives: ['Goblet Squats', 'Heel-Elevated Squats'],
      },
      {
        name: 'Dumbbell Calf Raises',
        sets: 4,
        reps: '15-20',
        weight_suggestion: 'moderate',
        rest_seconds: 60,
        notes: 'Full stretch at bottom, pause at top',
        alternatives: ['Barbell Calf Raises', 'Single-Leg Calf Raises'],
      },
    ],
    cooldown: [
      'Quad stretch - 30 seconds each leg',
      'Hamstring stretch - 30 seconds each leg',
      'Pigeon pose - 45 seconds each side',
    ],
    tags: ['legs', 'ppl', 'lower-body', 'quads', 'hamstrings', 'glutes', 'muscle-building'],
  },

  // ============================================
  // POWERLIFTING FOCUS
  // ============================================
  {
    id: 'strength-squat-focus',
    name: 'Squat Focus Day',
    description: 'Powerlifting-style squat day with accessories for quad and glute development.',
    category: 'strength',
    difficulty: 'advanced',
    duration_minutes: 70,
    equipment_needed: ['Olympic Barbell', 'Squat Rack', 'Safety Bars', 'Adjustable Dumbbells'],
    target_muscles: ['Quadriceps', 'Glutes', 'Core'],
    rest_between_exercises_seconds: 180,
    warmup: [
      'Foam roll quads and glutes - 2 minutes',
      'Goblet squats - 2x10',
      'Hip airplanes - 8 each side',
      'Empty barbell squats - 2x5',
      'Gradually ramp up weight over 3-4 sets',
    ],
    exercises: [
      {
        name: 'Barbell Back Squat',
        sets: 5,
        reps: '3-5',
        weight_suggestion: 'heavy',
        rest_seconds: 240,
        notes: 'Working sets at 80-85% 1RM. Focus on technique and bracing.',
        alternatives: ['Safety Bar Squat'],
      },
      {
        name: 'Pause Squats',
        sets: 3,
        reps: '5',
        weight_suggestion: 'moderate',
        rest_seconds: 180,
        notes: '3 second pause in the hole, about 70% of working weight',
        alternatives: ['Tempo Squats'],
      },
      {
        name: 'Front Squats',
        sets: 3,
        reps: '8',
        weight_suggestion: 'moderate',
        rest_seconds: 120,
        notes: 'Builds quad strength and upright torso',
        alternatives: ['Goblet Squats', 'Zercher Squats'],
      },
      {
        name: 'Bulgarian Split Squats',
        sets: 3,
        reps: '10 each leg',
        weight_suggestion: 'moderate',
        rest_seconds: 90,
        notes: 'Rear foot elevated on bench',
        alternatives: ['Walking Lunges'],
      },
      {
        name: 'Leg Extensions (seated dumbbell alternative)',
        sets: 3,
        reps: '15',
        weight_suggestion: 'light',
        rest_seconds: 60,
        notes: 'Sit on bench edge, extend legs with dumbbell between feet',
        alternatives: ['Sissy Squats', 'Wall Sits'],
      },
    ],
    cooldown: [
      'Couch stretch - 2 minutes each side',
      'Deep squat hold - 2 minutes',
      'Standing quad stretch - 1 minute each',
    ],
    notes:
      'For peaking, reduce volume and increase intensity. For building, increase volume with moderate weights.',
    tags: ['powerlifting', 'squat', 'strength', 'competition', 'advanced'],
  },

  {
    id: 'strength-bench-focus',
    name: 'Bench Press Focus Day',
    description: 'Powerlifting-style bench day with tricep and chest accessories.',
    category: 'strength',
    difficulty: 'advanced',
    duration_minutes: 65,
    equipment_needed: ['Olympic Barbell', 'Incline Bench', 'Flat Bench', 'Adjustable Dumbbells', 'Squat Rack'],
    target_muscles: ['Chest', 'Triceps', 'Shoulders'],
    rest_between_exercises_seconds: 180,
    warmup: [
      'Shoulder dislocates with band - 15 reps',
      'Push-ups - 2x10',
      'Empty bar bench press - 2x10',
      'Gradually ramp up weight over 3-4 sets',
    ],
    exercises: [
      {
        name: 'Barbell Bench Press',
        sets: 5,
        reps: '3-5',
        weight_suggestion: 'heavy',
        rest_seconds: 240,
        notes: 'Working sets at 80-85% 1RM. Leg drive, arch, tight upper back.',
        alternatives: ['Floor Press'],
      },
      {
        name: 'Close-Grip Bench Press',
        sets: 4,
        reps: '6-8',
        weight_suggestion: 'moderate',
        rest_seconds: 120,
        notes: 'Hands shoulder-width apart, emphasizes triceps and lockout strength',
        alternatives: ['JM Press'],
      },
      {
        name: 'Incline Dumbbell Press',
        sets: 3,
        reps: '10-12',
        weight_suggestion: 'moderate',
        rest_seconds: 90,
        notes: 'Builds upper chest and front delt',
        alternatives: ['Incline Barbell Press'],
      },
      {
        name: 'Dumbbell Flyes',
        sets: 3,
        reps: '12-15',
        weight_suggestion: 'light',
        rest_seconds: 60,
        notes: 'Stretch at bottom, slight bend in elbows',
        alternatives: ['Cable Flyes'],
      },
      {
        name: 'Dips (bench dips if no dip station)',
        sets: 3,
        reps: '10-15',
        weight_suggestion: 'bodyweight',
        rest_seconds: 60,
        notes: 'Lean forward for chest, upright for triceps',
        alternatives: ['Push-ups', 'Diamond Push-ups'],
      },
      {
        name: 'Overhead Tricep Extension',
        sets: 3,
        reps: '12-15',
        weight_suggestion: 'moderate',
        rest_seconds: 60,
        notes: 'Both hands on one dumbbell',
        alternatives: ['Skull Crushers'],
      },
    ],
    cooldown: [
      'Doorway chest stretch - 1 minute each side',
      'Tricep stretch - 30 seconds each arm',
      'Shoulder cross-body stretch - 30 seconds each',
    ],
    notes: 'Practice competition commands: Start, Press, Rack for meet prep.',
    tags: ['powerlifting', 'bench', 'strength', 'competition', 'advanced'],
  },

  {
    id: 'strength-deadlift-focus',
    name: 'Deadlift Focus Day',
    description: 'Powerlifting-style deadlift day with posterior chain accessories.',
    category: 'strength',
    difficulty: 'advanced',
    duration_minutes: 70,
    equipment_needed: ['Olympic Barbell', 'Squat Rack', 'Adjustable Dumbbells'],
    target_muscles: ['Back', 'Hamstrings', 'Glutes'],
    rest_between_exercises_seconds: 180,
    warmup: [
      'Foam roll back and hamstrings - 3 minutes',
      'Cat-cow - 10 reps',
      'Bird dogs - 8 each side',
      'Light Romanian deadlifts - 2x10',
      'Gradually ramp up deadlift weight over 4-5 sets',
    ],
    exercises: [
      {
        name: 'Conventional Deadlift',
        sets: 5,
        reps: '2-3',
        weight_suggestion: 'heavy',
        rest_seconds: 300,
        notes: 'Working sets at 80-90% 1RM. Reset each rep, no bounce.',
        alternatives: ['Sumo Deadlift', 'Trap Bar Deadlift'],
      },
      {
        name: 'Deficit Deadlifts',
        sets: 3,
        reps: '5',
        weight_suggestion: 'moderate',
        rest_seconds: 180,
        notes: 'Stand on 1-2 inch plate, builds strength off floor',
        alternatives: ['Pause Deadlifts'],
      },
      {
        name: 'Romanian Deadlifts',
        sets: 4,
        reps: '8-10',
        weight_suggestion: 'moderate',
        rest_seconds: 120,
        notes: 'Builds hamstring strength and hip hinge pattern',
        alternatives: ['Stiff-Leg Deadlifts'],
      },
      {
        name: 'Barbell Rows',
        sets: 4,
        reps: '8-10',
        weight_suggestion: 'moderate',
        rest_seconds: 90,
        notes: 'Maintains bent-over position, builds back thickness',
        alternatives: ['Pendlay Rows'],
      },
      {
        name: 'Back Extensions (use bench)',
        sets: 3,
        reps: '15',
        weight_suggestion: 'bodyweight',
        rest_seconds: 60,
        notes: 'Hook feet under rack, position on bench. Can hold dumbbell for resistance.',
        alternatives: ['Good Mornings', 'Reverse Hypers'],
      },
    ],
    cooldown: [
      'Child pose - 1 minute',
      'Seated hamstring stretch - 1 minute each leg',
      'Cat-cow - 10 reps slow',
    ],
    notes: 'For conventional deadlift: shins vertical, hips shoot back. Keep bar close to body.',
    tags: ['powerlifting', 'deadlift', 'strength', 'competition', 'advanced'],
  },

  // ============================================
  // FULL BODY ROUTINES
  // ============================================
  {
    id: 'strength-full-body-a',
    name: 'Full Body Strength A',
    description:
      'Balanced full body workout emphasizing squat and horizontal pressing. Great for 3-day programs.',
    category: 'full_body',
    difficulty: 'intermediate',
    duration_minutes: 60,
    equipment_needed: ['Olympic Barbell', 'Squat Rack', 'Safety Bars', 'Incline Bench', 'Adjustable Dumbbells'],
    target_muscles: ['Full Body'],
    rest_between_exercises_seconds: 120,
    warmup: [
      'Jump rope or rowing - 3 minutes',
      'World greatest stretch - 5 each side',
      'Arm circles - 20 each direction',
      'Bodyweight squats - 15 reps',
    ],
    exercises: [
      {
        name: 'Barbell Back Squat',
        sets: 4,
        reps: '6-8',
        weight_suggestion: 'heavy',
        rest_seconds: 180,
        notes: 'Primary lower body compound',
        alternatives: ['Front Squat', 'Goblet Squat'],
      },
      {
        name: 'Barbell Bench Press',
        sets: 4,
        reps: '6-8',
        weight_suggestion: 'heavy',
        rest_seconds: 120,
        notes: 'Primary horizontal push',
        alternatives: ['Dumbbell Bench Press'],
      },
      {
        name: 'Barbell Rows',
        sets: 3,
        reps: '8-10',
        weight_suggestion: 'moderate',
        rest_seconds: 90,
        notes: 'Primary horizontal pull',
        alternatives: ['Dumbbell Rows'],
      },
      {
        name: 'Romanian Deadlifts',
        sets: 3,
        reps: '10-12',
        weight_suggestion: 'moderate',
        rest_seconds: 90,
        notes: 'Hip hinge pattern, hamstring focus',
        alternatives: ['Good Mornings'],
      },
      {
        name: 'Dumbbell Lateral Raises',
        sets: 3,
        reps: '12-15',
        weight_suggestion: 'light',
        rest_seconds: 60,
        notes: 'Lateral delt isolation',
        alternatives: ['Upright Rows'],
      },
      {
        name: 'Plank',
        sets: 3,
        reps: '45 sec',
        weight_suggestion: 'bodyweight',
        rest_seconds: 45,
        notes: 'Core stability',
        alternatives: ['Dead Bug', 'Hollow Hold'],
      },
    ],
    cooldown: ['Full body stretch routine - 5 minutes'],
    tags: ['full-body', 'strength', '3-day-split', 'muscle-building'],
  },

  {
    id: 'strength-full-body-b',
    name: 'Full Body Strength B',
    description:
      'Balanced full body workout emphasizing deadlift and vertical pressing. Alternates with Full Body A.',
    category: 'full_body',
    difficulty: 'intermediate',
    duration_minutes: 60,
    equipment_needed: ['Olympic Barbell', 'Squat Rack', 'Safety Bars', 'Adjustable Dumbbells'],
    target_muscles: ['Full Body'],
    rest_between_exercises_seconds: 120,
    warmup: [
      'Jump rope or rowing - 3 minutes',
      'Hip circles - 10 each direction',
      'Shoulder dislocates - 15 reps',
      'Light deadlifts - 2x8',
    ],
    exercises: [
      {
        name: 'Deadlift',
        sets: 4,
        reps: '5',
        weight_suggestion: 'heavy',
        rest_seconds: 180,
        notes: 'Primary hip hinge compound',
        alternatives: ['Trap Bar Deadlift', 'Sumo Deadlift'],
      },
      {
        name: 'Overhead Press',
        sets: 4,
        reps: '6-8',
        weight_suggestion: 'heavy',
        rest_seconds: 120,
        notes: 'Primary vertical push',
        alternatives: ['Seated Dumbbell Press'],
      },
      {
        name: 'Pull-ups or Chin-ups',
        sets: 4,
        reps: '6-10',
        weight_suggestion: 'bodyweight',
        rest_seconds: 90,
        notes: 'Primary vertical pull. Use rack for assisted.',
        alternatives: ['Lat Pulldown', 'Inverted Rows'],
      },
      {
        name: 'Walking Lunges',
        sets: 3,
        reps: '10 each leg',
        weight_suggestion: 'moderate',
        rest_seconds: 90,
        notes: 'Unilateral leg work',
        alternatives: ['Bulgarian Split Squats'],
      },
      {
        name: 'Dumbbell Curls',
        sets: 3,
        reps: '12-15',
        weight_suggestion: 'moderate',
        rest_seconds: 60,
        notes: 'Bicep isolation',
        alternatives: ['Hammer Curls'],
      },
      {
        name: 'Ab Wheel or Barbell Rollout',
        sets: 3,
        reps: '10-12',
        weight_suggestion: 'bodyweight',
        rest_seconds: 60,
        notes: 'Use barbell with plates as ab wheel',
        alternatives: ['Plank', 'Dead Bug'],
      },
    ],
    cooldown: ['Full body stretch routine - 5 minutes'],
    tags: ['full-body', 'strength', '3-day-split', 'muscle-building'],
  },

  // ============================================
  // WEIGHT LOSS / METABOLIC
  // ============================================
  {
    id: 'strength-metabolic',
    name: 'Metabolic Strength Circuit',
    description:
      'Higher rep, lower rest strength training to maximize calorie burn while building muscle. Great for weight loss phases.',
    category: 'strength',
    difficulty: 'intermediate',
    duration_minutes: 45,
    equipment_needed: ['Olympic Barbell', 'Adjustable Dumbbells', 'Squat Rack'],
    target_muscles: ['Full Body'],
    rest_between_exercises_seconds: 45,
    warmup: [
      'Jumping jacks - 1 minute',
      'Bodyweight squats - 20 reps',
      'Push-ups - 10 reps',
      'Mountain climbers - 20 reps',
    ],
    exercises: [
      {
        name: 'Goblet Squats',
        sets: 4,
        reps: '15',
        weight_suggestion: 'moderate',
        rest_seconds: 45,
        notes: 'Keep tempo brisk but controlled',
        alternatives: ['Bodyweight Squats'],
      },
      {
        name: 'Push-ups',
        sets: 4,
        reps: '15-20',
        weight_suggestion: 'bodyweight',
        rest_seconds: 45,
        notes: 'Full range of motion',
        alternatives: ['Incline Push-ups', 'Bench Press'],
      },
      {
        name: 'Dumbbell Rows',
        sets: 4,
        reps: '12 each arm',
        weight_suggestion: 'moderate',
        rest_seconds: 45,
        notes: 'Alternating arms, keep core tight',
        alternatives: ['Barbell Rows'],
      },
      {
        name: 'Reverse Lunges',
        sets: 4,
        reps: '12 each leg',
        weight_suggestion: 'moderate',
        rest_seconds: 45,
        notes: 'Hold dumbbells at sides',
        alternatives: ['Walking Lunges'],
      },
      {
        name: 'Dumbbell Push Press',
        sets: 4,
        reps: '12',
        weight_suggestion: 'moderate',
        rest_seconds: 45,
        notes: 'Use leg drive to assist press',
        alternatives: ['Strict Press'],
      },
      {
        name: 'Mountain Climbers',
        sets: 3,
        reps: '30 sec',
        weight_suggestion: 'bodyweight',
        rest_seconds: 30,
        notes: 'Fast pace, keep hips level',
        alternatives: ['Burpees', 'High Knees'],
      },
    ],
    cooldown: ['Walk in place - 2 minutes', 'Full body stretch - 3 minutes'],
    notes:
      'Keep rest periods strict. Heart rate should stay elevated throughout. Great for calorie burning while preserving muscle.',
    tags: ['weight-loss', 'metabolic', 'circuit', 'fat-burning', 'strength'],
  },
];
