// HIIT Routines
// High-Intensity Interval Training using home gym equipment

import type { WorkoutRoutine } from './types';

export const HIIT_ROUTINES: WorkoutRoutine[] = [
  // ============================================
  // ROWING HIIT
  // ============================================
  {
    id: 'hiit-rowing-tabata',
    name: 'Rowing Tabata',
    description:
      'Classic Tabata protocol on the rowing machine. 20 seconds max effort, 10 seconds rest. Brutal but effective.',
    category: 'hiit',
    difficulty: 'advanced',
    duration_minutes: 20,
    equipment_needed: ['Rowing Machine'],
    target_muscles: ['Cardiovascular', 'Back', 'Core', 'Quadriceps'],
    rest_between_exercises_seconds: 10,
    warmup: [
      'Easy rowing - 5 minutes',
      '3 x 20 seconds at increasing intensity with 40 seconds easy',
      'Dynamic stretches - 2 minutes',
    ],
    exercises: [
      {
        name: 'Tabata Row Round 1',
        sets: 8,
        reps: '20 sec',
        weight_suggestion: 'max',
        rest_seconds: 10,
        notes: 'Maximum effort for 20 seconds, 10 seconds complete rest. 8 rounds = 4 minutes total.',
      },
      {
        name: 'Recovery Row',
        sets: 1,
        reps: '2 min',
        weight_suggestion: 'light',
        rest_seconds: 0,
        notes: 'Very easy rowing, catch your breath',
      },
      {
        name: 'Tabata Row Round 2',
        sets: 8,
        reps: '20 sec',
        weight_suggestion: 'max',
        rest_seconds: 10,
        notes: 'Second Tabata block. Push through the burn.',
      },
    ],
    cooldown: [
      'Very easy rowing - 3 minutes',
      'Walk around - 2 minutes',
      'Deep breathing exercises',
      'Full body stretch - 5 minutes',
    ],
    notes:
      'True Tabata requires 170% VO2max effort - you should be completely gassed by round 6-8. If you can easily complete both blocks, push harder.',
    tags: ['hiit', 'rowing', 'tabata', 'fat-burning', 'advanced', 'intense'],
  },

  {
    id: 'hiit-rowing-sprint-intervals',
    name: 'Rowing Sprint Intervals',
    description:
      'Short, explosive rowing sprints with rest intervals. Develops anaerobic power and burns maximum calories.',
    category: 'hiit',
    difficulty: 'intermediate',
    duration_minutes: 25,
    equipment_needed: ['Rowing Machine'],
    target_muscles: ['Cardiovascular', 'Back', 'Core', 'Quadriceps', 'Glutes'],
    rest_between_exercises_seconds: 30,
    warmup: [
      'Easy rowing - 4 minutes',
      '4 x 10-second sprint with 50 seconds easy',
      'Light stretching if needed',
    ],
    exercises: [
      {
        name: '100m Sprint',
        sets: 6,
        reps: '100m',
        weight_suggestion: 'max',
        rest_seconds: 45,
        notes: 'All-out sprint, maximum power. Should take 18-25 seconds.',
      },
      {
        name: 'Recovery Row',
        sets: 1,
        reps: '2 min',
        weight_suggestion: 'light',
        rest_seconds: 0,
        notes: 'Active recovery, easy pace',
      },
      {
        name: '200m Sprint',
        sets: 4,
        reps: '200m',
        weight_suggestion: 'heavy',
        rest_seconds: 60,
        notes: '90-95% effort. Should take 35-45 seconds.',
      },
      {
        name: 'Recovery Row',
        sets: 1,
        reps: '2 min',
        weight_suggestion: 'light',
        rest_seconds: 0,
        notes: 'Active recovery',
      },
      {
        name: '150m Sprint',
        sets: 4,
        reps: '150m',
        weight_suggestion: 'max',
        rest_seconds: 50,
        notes: 'Final push, leave nothing in the tank',
      },
    ],
    cooldown: ['Easy rowing - 3 minutes', 'Walk around - 2 minutes', 'Full body stretch - 4 minutes'],
    notes:
      'Focus on powerful leg drive and quick catch. Track your average split times and try to maintain consistency.',
    tags: ['hiit', 'rowing', 'sprints', 'power', 'intermediate', 'anaerobic'],
  },

  // ============================================
  // MIXED EQUIPMENT HIIT
  // ============================================
  {
    id: 'hiit-garage-gym-blast',
    name: 'Garage Gym HIIT Blast',
    description:
      'Full gym HIIT circuit using all available equipment. Combines strength and cardio for maximum calorie burn.',
    category: 'hiit',
    difficulty: 'intermediate',
    duration_minutes: 30,
    equipment_needed: ['Rowing Machine', 'Adjustable Dumbbells', 'Olympic Barbell', 'Incline Bench'],
    target_muscles: ['Full Body', 'Cardiovascular'],
    rest_between_exercises_seconds: 15,
    warmup: [
      'Easy rowing - 2 minutes',
      'Jumping jacks - 30 seconds',
      'Bodyweight squats - 15 reps',
      'Push-ups - 10 reps',
      'Arm circles - 20 each direction',
    ],
    exercises: [
      {
        name: 'Row Sprint',
        sets: 1,
        reps: '200m',
        weight_suggestion: 'heavy',
        rest_seconds: 15,
        notes: 'Start on rower, sprint 200m',
        alternatives: ['30 seconds hard row'],
      },
      {
        name: 'Dumbbell Thrusters',
        sets: 1,
        reps: '12',
        weight_suggestion: 'moderate',
        rest_seconds: 15,
        notes: 'Squat to press in one fluid motion',
        alternatives: ['Goblet Squat to Press'],
      },
      {
        name: 'Burpees',
        sets: 1,
        reps: '10',
        weight_suggestion: 'bodyweight',
        rest_seconds: 15,
        notes: 'Full burpee with jump',
        alternatives: ['Squat Thrusts'],
      },
      {
        name: 'Dumbbell Rows',
        sets: 1,
        reps: '10 each arm',
        weight_suggestion: 'moderate',
        rest_seconds: 15,
        notes: 'Explosive pull, controlled lower',
      },
      {
        name: 'Mountain Climbers',
        sets: 1,
        reps: '30 sec',
        weight_suggestion: 'bodyweight',
        rest_seconds: 15,
        notes: 'Fast pace',
      },
      {
        name: 'Dumbbell Push Press',
        sets: 1,
        reps: '12',
        weight_suggestion: 'moderate',
        rest_seconds: 15,
        notes: 'Use leg drive',
      },
    ],
    cooldown: ['Easy rowing - 2 minutes', 'Walk around - 1 minute', 'Full body stretch - 4 minutes'],
    notes:
      'Complete all 6 exercises as one circuit. Rest 90 seconds between rounds. Complete 4 rounds total. Adjust weights to maintain intensity throughout.',
    tags: ['hiit', 'circuit', 'full-body', 'fat-burning', 'intermediate'],
  },

  {
    id: 'hiit-barbell-complex',
    name: 'Barbell Complex HIIT',
    description:
      'Continuous barbell exercises without putting the bar down. Incredible metabolic demand and time-efficient.',
    category: 'hiit',
    difficulty: 'advanced',
    duration_minutes: 25,
    equipment_needed: ['Olympic Barbell', 'Squat Rack'],
    target_muscles: ['Full Body', 'Cardiovascular'],
    rest_between_exercises_seconds: 0,
    warmup: [
      'Jumping jacks - 1 minute',
      'Empty bar complex run-through - 1 round of 5 reps each',
      'Dynamic stretches - 2 minutes',
    ],
    exercises: [
      {
        name: 'Barbell Deadlift',
        sets: 5,
        reps: '6',
        weight_suggestion: 'moderate',
        rest_seconds: 0,
        notes: 'Start here, do not put bar down until complex is complete',
      },
      {
        name: 'Barbell Row',
        sets: 5,
        reps: '6',
        weight_suggestion: 'moderate',
        rest_seconds: 0,
        notes: 'Immediately into rows',
      },
      {
        name: 'Hang Clean',
        sets: 5,
        reps: '6',
        weight_suggestion: 'moderate',
        rest_seconds: 0,
        notes: 'Clean from hang position',
        alternatives: ['High Pull'],
      },
      {
        name: 'Front Squat',
        sets: 5,
        reps: '6',
        weight_suggestion: 'moderate',
        rest_seconds: 0,
        notes: 'Keep bar in front rack position',
      },
      {
        name: 'Push Press',
        sets: 5,
        reps: '6',
        weight_suggestion: 'moderate',
        rest_seconds: 0,
        notes: 'Use leg drive to get bar overhead',
      },
      {
        name: 'Back Squat',
        sets: 5,
        reps: '6',
        weight_suggestion: 'moderate',
        rest_seconds: 120,
        notes: 'Put bar on back, finish with squats. Then rest 2 minutes before next round.',
      },
    ],
    cooldown: [
      'Walk around - 2 minutes',
      'Light stretching - 3 minutes',
      'Focus on shoulders, hips, and back',
    ],
    notes:
      'Use a weight you can press for 8-10 reps. The complex is 36 total reps without putting the bar down. Complete 5 rounds total. Rest 2 minutes between complexes.',
    tags: ['hiit', 'barbell', 'complex', 'advanced', 'metabolic', 'strength-endurance'],
  },

  // ============================================
  // BODYWEIGHT HIIT
  // ============================================
  {
    id: 'hiit-bodyweight-burner',
    name: 'Bodyweight HIIT Burner',
    description:
      'No equipment needed HIIT workout. Pure bodyweight exercises for maximum portability and effectiveness.',
    category: 'hiit',
    difficulty: 'beginner',
    duration_minutes: 20,
    equipment_needed: ['Bodyweight'],
    target_muscles: ['Full Body', 'Cardiovascular'],
    rest_between_exercises_seconds: 10,
    warmup: [
      'March in place - 1 minute',
      'Arm circles - 30 seconds',
      'Leg swings - 10 each',
      'Bodyweight squats - 10 reps',
    ],
    exercises: [
      {
        name: 'Jumping Jacks',
        sets: 4,
        reps: '30 sec',
        weight_suggestion: 'bodyweight',
        rest_seconds: 10,
        notes: 'Full range of motion',
        alternatives: ['Step Jacks'],
      },
      {
        name: 'Squat Jumps',
        sets: 4,
        reps: '30 sec',
        weight_suggestion: 'bodyweight',
        rest_seconds: 10,
        notes: 'Land soft, explode up',
        alternatives: ['Air Squats'],
      },
      {
        name: 'Push-ups',
        sets: 4,
        reps: '30 sec',
        weight_suggestion: 'bodyweight',
        rest_seconds: 10,
        notes: 'As many quality reps as possible',
        alternatives: ['Knee Push-ups'],
      },
      {
        name: 'High Knees',
        sets: 4,
        reps: '30 sec',
        weight_suggestion: 'bodyweight',
        rest_seconds: 10,
        notes: 'Drive knees up, pump arms',
        alternatives: ['Marching'],
      },
      {
        name: 'Burpees',
        sets: 4,
        reps: '30 sec',
        weight_suggestion: 'bodyweight',
        rest_seconds: 10,
        notes: 'Full burpee or modify as needed',
        alternatives: ['Squat Thrusts'],
      },
      {
        name: 'Mountain Climbers',
        sets: 4,
        reps: '30 sec',
        weight_suggestion: 'bodyweight',
        rest_seconds: 10,
        notes: 'Fast pace, keep hips stable',
        alternatives: ['Plank Holds'],
      },
    ],
    cooldown: ['Walk in place - 2 minutes', 'Deep breathing - 1 minute', 'Full body stretch - 3 minutes'],
    notes:
      'Each exercise is 30 seconds work, 10 seconds rest. Complete all 6 exercises, rest 60 seconds, repeat for 4 total rounds.',
    tags: ['hiit', 'bodyweight', 'no-equipment', 'beginner', 'fat-burning'],
  },

  {
    id: 'hiit-dumbbell-devastator',
    name: 'Dumbbell Devastator',
    description:
      'High-intensity dumbbell circuit hitting all major muscle groups. Builds strength and conditioning simultaneously.',
    category: 'hiit',
    difficulty: 'intermediate',
    duration_minutes: 30,
    equipment_needed: ['Adjustable Dumbbells'],
    target_muscles: ['Full Body', 'Cardiovascular'],
    rest_between_exercises_seconds: 15,
    warmup: [
      'Jumping jacks - 1 minute',
      'Arm circles with light dumbbells - 30 seconds each direction',
      'Goblet squats - 10 reps',
      'Dumbbell RDL - 10 reps light',
    ],
    exercises: [
      {
        name: 'Dumbbell Snatch',
        sets: 1,
        reps: '8 each arm',
        weight_suggestion: 'moderate',
        rest_seconds: 15,
        notes: 'Explosive hip drive, catch overhead',
        alternatives: ['Dumbbell High Pull'],
      },
      {
        name: 'Goblet Squat',
        sets: 1,
        reps: '15',
        weight_suggestion: 'moderate',
        rest_seconds: 15,
        notes: 'Deep squat, chest up',
      },
      {
        name: 'Renegade Rows',
        sets: 1,
        reps: '10 each arm',
        weight_suggestion: 'moderate',
        rest_seconds: 15,
        notes: 'Plank position, alternate rows',
      },
      {
        name: 'Dumbbell Push Press',
        sets: 1,
        reps: '12',
        weight_suggestion: 'moderate',
        rest_seconds: 15,
        notes: 'Use leg drive to press overhead',
      },
      {
        name: 'Dumbbell Swings',
        sets: 1,
        reps: '20',
        weight_suggestion: 'moderate',
        rest_seconds: 15,
        notes: 'Hip hinge, power from glutes',
        alternatives: ['Kettlebell Swings'],
      },
      {
        name: 'Devil Press',
        sets: 1,
        reps: '8',
        weight_suggestion: 'moderate',
        rest_seconds: 15,
        notes: 'Burpee with dumbbells, snatch to overhead at top',
        alternatives: ['Dumbbell Burpee'],
      },
    ],
    cooldown: ['Walk around - 2 minutes', 'Light stretching - 3 minutes', 'Deep breathing'],
    notes:
      'Complete all 6 exercises as a circuit. Rest 90 seconds between rounds. Complete 4 rounds. Choose a challenging but sustainable weight.',
    tags: ['hiit', 'dumbbells', 'circuit', 'intermediate', 'metabolic', 'strength-endurance'],
  },
];
