// Minimal recipe data for initial bundle
// Contains 2-3 recipes per category for instant display
// Full recipe data is lazy-loaded from public/data/recipes/*.json

import type { Recipe } from './types';

// 3 breakfast recipes for initial render
export const INITIAL_BREAKFAST_RECIPES: Recipe[] = [
  {
    id: 'breakfast-0001',
    name: 'Classic Protein Pancakes',
    description: 'Fluffy pancakes packed with protein, perfect for muscle building',
    category: 'breakfast',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 2,
    baseServings: 2,
    ingredients: [
      { item: 'Oats', quantity: 1, unit: 'cup' },
      { item: 'Whey Protein Powder', quantity: 1, unit: 'scoop' },
      { item: 'Egg Whites', quantity: 4, unit: 'large' },
      { item: 'Greek Yogurt', quantity: 0.5, unit: 'cup' },
      { item: 'Baking Powder', quantity: 1, unit: 'tsp' },
      { item: 'Vanilla Extract', quantity: 1, unit: 'tsp' },
      { item: 'Mixed Berries', quantity: 0.5, unit: 'cup', notes: 'for topping' },
    ],
    instructions: [
      'Blend oats in a food processor until they form a flour-like consistency.',
      'Add protein powder, egg whites, Greek yogurt, baking powder, and vanilla. Blend until smooth.',
      'Heat a non-stick pan over medium heat and lightly coat with cooking spray.',
      'Pour 1/4 cup batter per pancake onto the pan.',
      'Cook until bubbles form on the surface, about 2-3 minutes, then flip.',
      'Cook another 1-2 minutes until golden brown.',
      'Serve topped with mixed berries.',
    ],
    nutrition: { calories: 420, protein_g: 38, carbs_g: 45, fat_g: 8, fiber_g: 6 },
    macrosPerServing: { calories: 210, protein: 19, carbs: 23, fat: 4, fiber: 3 },
    difficulty: 'easy',
    tags: ['high-protein', 'muscle-building', 'meal-prep'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'breakfast-0002',
    name: 'Overnight Protein Oats',
    description: 'No-cook overnight oats with extra protein for busy mornings',
    category: 'breakfast',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    baseServings: 1,
    ingredients: [
      { item: 'Rolled Oats', quantity: 0.5, unit: 'cup' },
      { item: 'Whey Protein Powder', quantity: 1, unit: 'scoop' },
      { item: 'Greek Yogurt', quantity: 0.5, unit: 'cup' },
      { item: 'Almond Milk', quantity: 0.5, unit: 'cup' },
      { item: 'Chia Seeds', quantity: 1, unit: 'tbsp' },
      { item: 'PB Fit', quantity: 2, unit: 'tbsp' },
      { item: 'Mixed Berries', quantity: 0.25, unit: 'cup' },
    ],
    instructions: [
      'In a jar or container, combine oats, protein powder, Greek yogurt, and almond milk.',
      'Stir in chia seeds and PB Fit until well combined.',
      'Cover and refrigerate overnight, or at least 4 hours.',
      'In the morning, top with mixed berries.',
      'Can be eaten cold or microwaved for 1-2 minutes.',
    ],
    nutrition: { calories: 485, protein_g: 42, carbs_g: 52, fat_g: 12, fiber_g: 10 },
    macrosPerServing: { calories: 485, protein: 42, carbs: 52, fat: 12, fiber: 10 },
    difficulty: 'easy',
    tags: ['high-protein', 'meal-prep', 'quick', 'no-cook'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'breakfast-0003',
    name: 'High-Protein Egg Muffins',
    description: 'Portable egg muffins loaded with veggies and protein',
    category: 'breakfast',
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 6,
    baseServings: 6,
    ingredients: [
      { item: 'Eggs', quantity: 8, unit: 'large' },
      { item: 'Egg Whites', quantity: 4, unit: 'large' },
      { item: 'Turkey Sausage', quantity: 4, unit: 'oz', notes: 'cooked and crumbled' },
      { item: 'Bell Peppers', quantity: 0.5, unit: 'cup', notes: 'diced' },
      { item: 'Spinach', quantity: 1, unit: 'cup', notes: 'chopped' },
      { item: 'Cheddar Cheese', quantity: 0.5, unit: 'cup', notes: 'shredded, low-fat' },
    ],
    instructions: [
      'Preheat oven to 350F (175C) and grease a 12-cup muffin tin.',
      'In a large bowl, whisk together eggs and egg whites.',
      'Stir in cooked turkey sausage, bell peppers, spinach, and onion.',
      'Divide mixture evenly among muffin cups (about 2/3 full).',
      'Sprinkle cheese on top of each.',
      'Bake for 22-25 minutes until set and slightly golden.',
      'Store in refrigerator for up to 5 days.',
    ],
    nutrition: { calories: 180, protein_g: 16, carbs_g: 3, fat_g: 11, fiber_g: 1 },
    macrosPerServing: { calories: 180, protein: 16, carbs: 3, fat: 11, fiber: 1 },
    difficulty: 'easy',
    tags: ['high-protein', 'meal-prep', 'low-carb', 'portable'],
    created_at: '2024-01-01T00:00:00Z',
  },
];

// 3 lunch recipes for initial render
export const INITIAL_LUNCH_RECIPES: Recipe[] = [
  {
    id: 'lunch-0001',
    name: 'Classic Chicken Caesar Salad',
    description: 'Crispy romaine with grilled chicken, parmesan, and homemade caesar dressing',
    category: 'lunch',
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 2,
    baseServings: 2,
    ingredients: [
      { item: 'Chicken Breast', quantity: 1, unit: 'lb' },
      { item: 'Romaine Lettuce', quantity: 2, unit: 'hearts' },
      { item: 'Parmesan Cheese', quantity: 0.5, unit: 'cup', notes: 'shaved' },
      { item: 'Greek Yogurt', quantity: 0.25, unit: 'cup' },
      { item: 'Lemon Juice', quantity: 2, unit: 'tbsp' },
      { item: 'Garlic', quantity: 2, unit: 'cloves', notes: 'minced' },
      { item: 'Olive Oil', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Season chicken breast with salt and pepper.',
      'Grill or pan-sear chicken for 6-7 minutes per side until internal temp reaches 165F.',
      'Let chicken rest for 5 minutes, then slice.',
      'Make dressing: whisk together Greek yogurt, lemon juice, garlic, and olive oil.',
      'Chop romaine lettuce and place in a large bowl.',
      'Toss lettuce with dressing until well coated.',
      'Top with sliced chicken and shaved parmesan.',
    ],
    nutrition: { calories: 520, protein_g: 48, carbs_g: 18, fat_g: 28, fiber_g: 4 },
    macrosPerServing: { calories: 260, protein: 24, carbs: 9, fat: 14, fiber: 2 },
    difficulty: 'easy',
    tags: ['high-protein', 'low-carb', 'salad', 'classic'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'lunch-0002',
    name: 'Turkey Avocado Wrap',
    description: 'Lean turkey with creamy avocado in a whole grain wrap',
    category: 'lunch',
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    servings: 2,
    baseServings: 2,
    ingredients: [
      { item: 'Turkey Breast (Deli)', quantity: 0.5, unit: 'lb' },
      { item: 'Whole Wheat Tortillas', quantity: 2, unit: 'large' },
      { item: 'Avocado', quantity: 1, unit: 'medium' },
      { item: 'Spinach', quantity: 2, unit: 'cups' },
      { item: 'Tomato', quantity: 1, unit: 'medium', notes: 'sliced' },
      { item: 'Mustard', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Lay tortillas flat on a clean surface.',
      'Spread mustard on each tortilla.',
      'Layer turkey slices in the center.',
      'Add spinach, tomato slices, and avocado.',
      'Fold sides in and roll up tightly.',
      'Cut in half diagonally and serve.',
    ],
    nutrition: { calories: 420, protein_g: 32, carbs_g: 36, fat_g: 18, fiber_g: 10 },
    macrosPerServing: { calories: 210, protein: 16, carbs: 18, fat: 9, fiber: 5 },
    difficulty: 'easy',
    tags: ['high-protein', 'quick', 'portable', 'no-cook'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'lunch-0003',
    name: 'Tuna Stuffed Avocado',
    description: 'Protein-rich tuna salad served in fresh avocado halves',
    category: 'lunch',
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    servings: 2,
    baseServings: 2,
    ingredients: [
      { item: 'Canned Tuna', quantity: 2, unit: 'cans', notes: 'drained' },
      { item: 'Avocado', quantity: 2, unit: 'large' },
      { item: 'Greek Yogurt', quantity: 2, unit: 'tbsp' },
      { item: 'Celery', quantity: 0.25, unit: 'cup', notes: 'diced' },
      { item: 'Red Onion', quantity: 2, unit: 'tbsp', notes: 'diced' },
      { item: 'Lemon Juice', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Mix tuna with Greek yogurt, celery, red onion, and lemon juice.',
      'Season with salt and pepper to taste.',
      'Cut avocados in half and remove the pit.',
      'Fill each avocado half with tuna mixture.',
      'Serve immediately or chill for 30 minutes.',
    ],
    nutrition: { calories: 480, protein_g: 38, carbs_g: 16, fat_g: 30, fiber_g: 10 },
    macrosPerServing: { calories: 240, protein: 19, carbs: 8, fat: 15, fiber: 5 },
    difficulty: 'easy',
    tags: ['high-protein', 'low-carb', 'quick', 'no-cook', 'keto-friendly'],
    created_at: '2024-01-01T00:00:00Z',
  },
];

// 3 dinner recipes for initial render
export const INITIAL_DINNER_RECIPES: Recipe[] = [
  {
    id: 'dinner-0001',
    name: 'Grilled Chicken Breast with Roasted Vegetables',
    description: 'Juicy grilled chicken breast served with a colorful medley of roasted vegetables',
    category: 'dinner',
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 4,
    baseServings: 4,
    ingredients: [
      { item: 'Chicken Breast', quantity: 4, unit: 'pieces', notes: 'boneless, skinless' },
      { item: 'Broccoli', quantity: 2, unit: 'cups', notes: 'florets' },
      { item: 'Bell Peppers', quantity: 2, unit: 'medium', notes: 'mixed colors, diced' },
      { item: 'Zucchini', quantity: 1, unit: 'large', notes: 'sliced' },
      { item: 'Olive Oil', quantity: 3, unit: 'tbsp' },
      { item: 'Garlic', quantity: 4, unit: 'cloves', notes: 'minced' },
      { item: 'Italian Seasoning', quantity: 2, unit: 'tsp' },
    ],
    instructions: [
      'Preheat oven to 425F (220C) and preheat grill or grill pan to medium-high.',
      'Toss vegetables with 2 tbsp olive oil, garlic, and Italian seasoning.',
      'Spread vegetables on a baking sheet and roast for 25-30 minutes, stirring halfway.',
      'Brush chicken breasts with remaining olive oil. Season with salt and pepper.',
      'Grill chicken for 6-7 minutes per side until internal temperature reaches 165F.',
      'Let chicken rest for 5 minutes before slicing.',
      'Serve chicken over roasted vegetables.',
    ],
    nutrition: { calories: 320, protein_g: 42, carbs_g: 12, fat_g: 12, fiber_g: 4 },
    macrosPerServing: { calories: 320, protein: 42, carbs: 12, fat: 12, fiber: 4 },
    difficulty: 'easy',
    tags: ['high-protein', 'low-carb', 'muscle-building', 'meal-prep'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dinner-0002',
    name: 'Salmon with Quinoa and Asparagus',
    description: 'Omega-3 rich salmon fillet served with fluffy quinoa and tender asparagus',
    category: 'dinner',
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    baseServings: 4,
    ingredients: [
      { item: 'Salmon Fillets', quantity: 4, unit: 'pieces', notes: '6 oz each' },
      { item: 'Quinoa', quantity: 1.5, unit: 'cups' },
      { item: 'Asparagus', quantity: 1, unit: 'bunch' },
      { item: 'Lemon', quantity: 2, unit: 'medium' },
      { item: 'Olive Oil', quantity: 3, unit: 'tbsp' },
      { item: 'Dill', quantity: 2, unit: 'tbsp', notes: 'fresh, chopped' },
    ],
    instructions: [
      'Cook quinoa according to package directions.',
      'Preheat oven to 400F (200C).',
      'Place salmon fillets on a lined baking sheet.',
      'Season with salt, pepper, and drizzle with olive oil.',
      'Bake salmon and asparagus for 12-15 minutes.',
      'Serve salmon over quinoa with asparagus on the side.',
      'Garnish with fresh dill and lemon wedges.',
    ],
    nutrition: { calories: 480, protein_g: 40, carbs_g: 32, fat_g: 20, fiber_g: 5 },
    macrosPerServing: { calories: 480, protein: 40, carbs: 32, fat: 20, fiber: 5 },
    difficulty: 'easy',
    tags: ['high-protein', 'omega-3', 'heart-healthy', 'gluten-free'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dinner-0003',
    name: 'Lean Beef Stir Fry with White Rice',
    description: 'Quick and easy beef stir fry with colorful vegetables served over white rice',
    category: 'dinner',
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 4,
    baseServings: 4,
    ingredients: [
      { item: 'Lean Beef (Sirloin)', quantity: 1, unit: 'lb', notes: 'sliced thin' },
      { item: 'White Rice', quantity: 2, unit: 'cups' },
      { item: 'Stir Fry Vegetables', quantity: 4, unit: 'cups' },
      { item: 'Soy Sauce (Low Sodium)', quantity: 3, unit: 'tbsp' },
      { item: 'Sesame Oil', quantity: 1, unit: 'tbsp' },
      { item: 'Ginger', quantity: 1, unit: 'tbsp', notes: 'freshly grated' },
      { item: 'Garlic', quantity: 3, unit: 'cloves', notes: 'minced' },
    ],
    instructions: [
      'Cook white rice according to package directions.',
      'Heat sesame oil in a wok or large skillet over high heat.',
      'Add beef strips and stir fry until browned, about 3-4 minutes. Remove and set aside.',
      'Add vegetables, ginger, and garlic. Stir fry for 4-5 minutes.',
      'Return beef to the wok, pour soy sauce over everything.',
      'Stir fry for 1-2 minutes until heated through.',
      'Serve over white rice.',
    ],
    nutrition: { calories: 450, protein_g: 35, carbs_g: 48, fat_g: 14, fiber_g: 4 },
    macrosPerServing: { calories: 450, protein: 35, carbs: 48, fat: 14, fiber: 4 },
    difficulty: 'easy',
    tags: ['high-protein', 'quick', 'weeknight'],
    created_at: '2024-01-01T00:00:00Z',
  },
];

// 3 snack recipes for initial render
export const INITIAL_SNACK_RECIPES: Recipe[] = [
  {
    id: 'snack-0001',
    name: 'No-Bake Protein Energy Balls',
    description: 'Chewy protein-packed bites perfect for pre-workout fuel',
    category: 'snack',
    prep_time_minutes: 15,
    cook_time_minutes: 0,
    servings: 12,
    baseServings: 12,
    ingredients: [
      { item: 'Rolled Oats', quantity: 1, unit: 'cup' },
      { item: 'Whey Protein Powder', quantity: 2, unit: 'scoops' },
      { item: 'PB Fit', quantity: 0.5, unit: 'cup' },
      { item: 'Honey', quantity: 0.25, unit: 'cup' },
      { item: 'Mini Chocolate Chips', quantity: 0.25, unit: 'cup' },
      { item: 'Chia Seeds', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Combine oats, protein powder, PB Fit, and chia seeds in a large bowl.',
      'Add honey and mix until combined.',
      'Fold in chocolate chips.',
      'Roll into 12 balls, about 1.5 inches each.',
      'Refrigerate for at least 30 minutes before serving.',
      'Store in refrigerator for up to 1 week.',
    ],
    nutrition: { calories: 1440, protein_g: 72, carbs_g: 168, fat_g: 48, fiber_g: 24 },
    macrosPerServing: { calories: 120, protein: 6, carbs: 14, fat: 4, fiber: 2 },
    difficulty: 'easy',
    tags: ['high-protein', 'no-cook', 'meal-prep', 'portable', 'pre-workout'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'snack-0002',
    name: 'Greek Yogurt Protein Parfait',
    description: 'Layered parfait with Greek yogurt, berries, and granola',
    category: 'snack',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    baseServings: 1,
    ingredients: [
      { item: 'Greek Yogurt (Plain)', quantity: 1, unit: 'cup' },
      { item: 'Mixed Berries', quantity: 0.5, unit: 'cup' },
      { item: 'Low-Sugar Granola', quantity: 0.25, unit: 'cup' },
      { item: 'Whey Protein Powder', quantity: 0.5, unit: 'scoop', notes: 'vanilla' },
      { item: 'Honey', quantity: 1, unit: 'tsp', notes: 'optional' },
    ],
    instructions: [
      'Stir protein powder into Greek yogurt until smooth.',
      'Layer half the yogurt in a glass or bowl.',
      'Add half the berries and half the granola.',
      'Repeat layers with remaining ingredients.',
      'Drizzle with honey if desired.',
      'Serve immediately or refrigerate for up to 2 hours.',
    ],
    nutrition: { calories: 320, protein_g: 32, carbs_g: 38, fat_g: 6, fiber_g: 5 },
    macrosPerServing: { calories: 320, protein: 32, carbs: 38, fat: 6, fiber: 5 },
    difficulty: 'easy',
    tags: ['high-protein', 'quick', 'no-cook', 'post-workout'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'snack-0003',
    name: 'Protein-Packed Cottage Cheese Bowl',
    description: 'Cottage cheese topped with fruit and a drizzle of honey',
    category: 'snack',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    baseServings: 1,
    ingredients: [
      { item: 'Cottage Cheese (Low-Fat)', quantity: 1, unit: 'cup' },
      { item: 'Fresh Berries', quantity: 0.5, unit: 'cup' },
      { item: 'Almonds', quantity: 2, unit: 'tbsp', notes: 'sliced' },
      { item: 'Honey', quantity: 1, unit: 'tsp' },
      { item: 'Cinnamon', quantity: 0.25, unit: 'tsp' },
    ],
    instructions: [
      'Add cottage cheese to a bowl.',
      'Top with fresh berries and sliced almonds.',
      'Drizzle with honey.',
      'Sprinkle cinnamon on top.',
      'Serve immediately.',
    ],
    nutrition: { calories: 280, protein_g: 28, carbs_g: 24, fat_g: 8, fiber_g: 3 },
    macrosPerServing: { calories: 280, protein: 28, carbs: 24, fat: 8, fiber: 3 },
    difficulty: 'easy',
    tags: ['high-protein', 'quick', 'no-cook', 'low-calorie'],
    created_at: '2024-01-01T00:00:00Z',
  },
];

// Combined minimal recipe collection (12 recipes total)
export const INITIAL_RECIPES: Recipe[] = [
  ...INITIAL_BREAKFAST_RECIPES,
  ...INITIAL_LUNCH_RECIPES,
  ...INITIAL_DINNER_RECIPES,
  ...INITIAL_SNACK_RECIPES,
];

// Count of minimal recipes for stats display
export const INITIAL_RECIPE_COUNTS = {
  total: INITIAL_RECIPES.length,
  breakfast: INITIAL_BREAKFAST_RECIPES.length,
  lunch: INITIAL_LUNCH_RECIPES.length,
  dinner: INITIAL_DINNER_RECIPES.length,
  snack: INITIAL_SNACK_RECIPES.length,
};
